---
title: "Merced River Redd Site Selection"
author: "Rosealea Bond"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  github_document:
    toc: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "readme-figs/"
)
```


## General Goals

The main goal is to perform a logistic regression investigating redd presence (redd=1) and absence (redd=0). Potential parameters include depth, velocity, csi, wsg, dar, and site (Merced River Ranch (mrr) and Robinson Reach (rr)). The steps include generating a candidate set of models, run AIC, and additional statistics as needed. This analysis is similar to Benjankar et al., (2016). The GIT repository can be found here https://github.com/RMBond/Merced_Redd_selection.git

      
**Description of Datasets:**  
Logistic Regression input file **mHabVarsSite.csv** was generated by L. Harrison on 14 February 2019. 
The script **Redd_logisticregression.R** was created to run the logistic regression analysis.


## Interpolate a grainsize raster
Currently there are two grainsize datasets. DWR from 2012 and Sam Emerson's thesis pebble count data from 2015. The DWR data is summarized to one `D50` and one `D84` value for each cross section, while Emerson's data has pebble count in the outer, middle and inner positions of each bend. 

The goal here is to recalculate a `D50` and `D84` for each position/bend combination. From there we will use ArcGIS to merge the two pebble count datasets into one point shapefile, then interpolate a TIN and DEM within the wetted channel. 

**Note:** for now I am not uploading any of the spatial data to this repo, but can do that if it seems like it makes sense.

## Next To Do's

1. Other candidate models? Interactions?
2. Additional statistics? (Wald statistic?)


